spring.application.name=finflow
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
finflow.transfer.daily-limit=100000.00
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/finflow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Cache TTL (Time-To-Live) in milliseconds - 10 minutes
spring.cache.redis.time-to-live=600000
